version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
  zookeeper:
    image: zookeeper:3.4.14
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
